### PR TITLE
B bimanual fix

### LINKED ISSUE #167: fix controllers and tranmissions for bimanual systems
Currently it is assumed that the joint name has 4 letters and the fourth is the joint number. In a bimanual system FFJ0 for example will be rhFFJ0. So now the last letter of a variable length string will be the joint number.

### PR DESCRIPTION
**Pull request by shadowmanos**
closed #167

### CODE REVIEW

File: sr_mechanism_controllers/src/sr_friction_compensation.cpp [hunk 1]
```diff
@@ -3,21 +3,21 @@
...
-*
-* This program is distributed in the hope that it will be useful, but WITHOUT
-* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
-* more details.
-*
-* You should have received a copy of the GNU General Public License along
-* with this program.  If not, see <http://www.gnu.org/licenses/>.
-*
+ * Copyright 2011 Shadow Robot Company Ltd.
```
Comment (toliver) [inline sr_mechanism_controllers/src/sr_friction_compensation.cpp:6]: Please, do not reformat the indentation in the same PR where real changes are made. It makes the review unnecessarily difficult.
